### ISSUE TITLE
Help with Maintaining this Repo

### ISSUE THREAD

**Issue by donkidd** [dutchiexl/BehatHtmlFormatterPlugin#105]
This repo is great and I would love to help keep it moving forward.  If there are things to help with please let me know.

**Comment by chadyred** [comment]
This is also about simple two last PR : they are even simple as hell ! So it may be merge immediately !

https://github.com/dutchiexl/BehatHtmlFormatterPlugin/pull/106
https://github.com/dutchiexl/BehatHtmlFormatterPlugin/pull/104

**Comment by PurHur** [comment]
See #111 .

Do you want to maintain a fork?
