### ISSUE TITLE
On Windows renderer option is not recognized

### ISSUE THREAD

**Issue by tkhisamova** [dutchiexl/BehatHtmlFormatterPlugin#11]
On Windows renderer option is not recognized.
YML config contains:
    formatters:
        html:
            output_path: %paths.base%/../reports/
        pretty:
            output_path: %paths.base%/../reports/pretty.txt
    extensions:
      emuse\BehatHTMLFormatter\BehatHTMLFormatterExtension:
        name: html
        renderer: Behat2

The Invalid Configuration Exception is thrown as follows:
 [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
  Unrecognized option "renderer" under "testwork.emusehtml"

**Comment by dutchiexl** [comment]
Does it work when you remove the renderer parameter ?

**Comment by tkhisamova** [comment]
If the renderer parameter is removed, it works on Windows. Might the renderer be chosen by default on Windows?

?

**Comment by dutchiexl** [comment]
By default behat2 is chosen. I am assuming you indentation is wrong in your YML file. Can you please check that ?

**Comment by tkhisamova** [comment]
?YML config is fine. That might be displayed wrong in the message, but it is verified and cannot be a reason. And the renderer works well on Linux with the same config. Have you tested the renderer on Windows?

**Comment by dutchiexl** [comment]
When I copy paste your settings, I see different kind of indentations, can you send me you behat.yml file ?

**Comment by dutchiexl** [comment]
ok, I checked it, it is DEFINITELY an indentation problem. In your configuration, renderer is set as a parameter of 'name: html'. Please don't say: it is fine, it is verified, when it's not.

**Comment by tkhisamova** [comment]
I'm sending a behat YAML sample.

**Comment by tkhisamova** [comment]
Please let me know if you've received behatci.yml file to check. I am affraid it can be cut off by OWA.

If I inject an indention problem, the error text is different:

  [Symfony\Component\Yaml\Exception\ParseException]
  Unable to parse in "C:\Behat3\configs\behat.yml" at line <number>(near "  re
  nderer: Behat2").

or like that:

  [Symfony\Component\Yaml\Exception\ParseException]
  Indentation problem in "C:\Behat3\configs\behat.yml" at line <number> (near "
    renderer: Behat2").

But with the YAML file as I sent:

emuse\BehatHTMLFormatter\BehatHTMLFormatterExtension:
  name: html
  renderer: Behat2

the error is like that:
  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]
  Unrecognized option "renderer" under "testwork.emusehtml"  ?

What might be wrong on Windows? Thanks for any help.

**Comment by dutchiexl** [comment]
can you find the file BehatHtmlFormatterExtension.php and send me the code ?

## 

Neal Vanmeert
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by tkhisamova** [comment]
?BehatHTMLFormatterExtension.php? is attached. Do you think that's an old version?

I will check it too.

Thanks.

**Comment by dutchiexl** [comment]
I don’t receive you files, but yes, I think it is an old version. the configure function should look like this:
public function configure(ArrayNodeDefinition $builder) {
$builder->children()->scalarNode("name")->defaultValue("emusehtml");
$builder->children()->scalarNode("renderer")->defaultValue("behat2");
$builder->children()->scalarNode("file_name")->defaultValue("generated");
$builder->children()->scalarNode('output')->defaultValue('.');
}  

## 

Neal Vanmeert
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by tkhisamova** [comment]
Thanks, you're right.

The problem is that dev-master set in composer.json:

"emuse/behat-html-formatter": "dev-master"​

And when I have Behat allready installed and execute 'php composer.php install' having both composer.json and composer.lock, the plugin will not be updated. We have fixed the configuration to have absolutely same software for test machine and CI and avoid any surprises with third-party applications.  Could you please add the version control  for the plugin? My apologies for disturbing you. Thanks a lot for your help and invaluable plugin!

Regards,

Tatiana

**Comment by dutchiexl** [comment]
Did you forget to update composer ?

## 

Neal Vanmeert
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by dutchiexl** [comment]
just run “composer update"

## 

Neal Vanmeert
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by tkhisamova** [comment]
​I don't want to update it as it will retrieve updates for all plugins and might require changes in configuration and in code which cause problems. That makes test results not reproducible. I want to install specific version but as I cannot point to definite version number for behat html formatter plugin, that problem is revealed. If you could add version control that would be helpful!

Thanks, I have updated the plugin on Windows. It works great!

**Comment by dutchiexl** [comment]
If you want plugins to stay the same version, why don’t you tell composer to use that version?. Composer is meant to be updated, that is the normal flow of developing with composer and good practice. Imagine there are major security updates, and you don’t run them because your system is badly configured, you will let anyone hack your system then ?! I cannot add a version number only because it is convenient for one person. Composer is built to handle these situations though.

There are 2 ways of handling this:
- Put a definite version number behind every plugin you don’t want to update
- Fork my plugin, add a version number and use your own repository.

## 

Neal Vanmeert
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by tkhisamova** [comment]
​Actually composer.json has fixed versions for each plugin except for Behat formatter as  there is not version for it. Test framework should be stable, results should be reproducible. Our test environment is secure and not opened outside the company. We chase new changes and test them first prior to including them in CI. The idea with forking looks as workaround, but not sure if having 3rd party applications in the company's repository is approved by team lead. I'll check out that.

Thanks,

Tatiana
