### ISSUE TITLE
Maintainer 

### ISSUE THREAD

**Issue by PurHur** [dutchiexl/BehatHtmlFormatterPlugin#111]
Hello interested folks!

Lets start the discussion to get a new maintainer into this project. Since this project is used in a lot of testing backends a new maintainer would be great.

I would do it but I give priority to the contributors. Eventually we should fork this? Who wants to be the prince/princess?

**Comment by donkidd** [comment]
I'd be interested in helping with this.

**Comment by dutchiexl** [comment]
Hello all, I am very sorry for not beeing able to further maintain this. ATM I am not using behat myself so I am not very involved with the plugin. I can add maintainers if you like.

**Comment by PurHur** [comment]
Hello there! That would be the best. Dont let this package die, you made good work.

**Comment by donkidd** [comment]
@dutchiexl That sounds better then us having to fork this.  I'm guessing that @PurHur & I would be willing to start getting the repo going again.

**Comment by fr33ek** [comment]
@dutchiexl, yes, please add some :)

Btw, do you use some other framework for the same job? May be we also should? :)

**Comment by PurHur** [comment]
ok. My cloud is ready to generate some test reports!

**Comment by PurHur** [comment]
This is now going into production. Please help :)

**Comment by pmaasz** [comment]
Hey @dutchiexl, adding @PurHur and @donkidd as maintainers would keep this repo alive. I am interested in using and contributing to this project.

**Comment by PurHur** [comment]
@dutchiexl invited me today! Thanks a lot!

i cleaned up something, merged the fixes and now where here to headstart with a nice project. If you have features in mind just post it, im happy to merge your PRs.
