### ISSUE TITLE
Ability to configure the name of the html

### ISSUE THREAD

**Issue by rodrigoaguilera** [dutchiexl/BehatHtmlFormatterPlugin#12]
I'm using this plugin
https://wiki.jenkins-ci.org/display/JENKINS/HTML+Publisher+Plugin
And forces me to specify a index file.
Before it was report.html
Now it has a date and I cannot view the html.

I would like a way to make the name of this file predictable.

**Comment by dutchiexl** [comment]
I will add this functionality.

**Comment by rodrigoaguilera** [comment]
Thank you!

**Comment by dutchiexl** [comment]
It is updated, can you check it out ?

**Comment by rodrigoaguilera** [comment]
Woah, It works great!
Now that there is also a junit formatter behat 3 is in great shape
