### ISSUE TITLE
Fatal error when starting a behat test

### ISSUE THREAD

**Issue by gdobiecki** [dutchiexl/BehatHtmlFormatterPlugin#13]
Hi guys,
Recently I get an error when I run behat tests. Message is 
PHP Fatal error:  Class 'emuse\BehatHTMLFormatter\Renderer\behat2Renderer' not found in /home/grzegorzdobiecki/projekty/nse-learning-services-client/vendors_behat/emuse/behat-html-formatter/src/Renderer/BaseRenderer.php on line 44
I found class Behat2Renderer (capital B) in vendors.
HEAD is at
commit f3bcf07bf38e895cfa7e301ee1e61d4e86ca9aa0
Author: Neal Vanmeert neal@emuse.be
Date:   Fri Mar 20 14:20:21 2015 +0100

But I notice that is worked when HEAD was at commit 801cc56ef937096c5ba2a7d12eba2d03e1a499ea

**Comment by Trogie** [comment]
Yes same problem

check:
https://github.com/dutchiexl/BehatHtmlFormatterPlugin/compare/master...Trogie:patch-1

**Comment by Trogie** [comment]
Or make sure you have the renderer configuration set up correctly in behat.yml

**Comment by dutchiexl** [comment]
I will look into this today

**Comment by dutchiexl** [comment]
Can someone with the problem post his/hers behat configuration ?

**Comment by Trogie** [comment]
first i only had (with the class error behat2Renderer):
        emuse\BehatHTMLFormatter\BehatHTMLFormatterExtension:
            name: html

Second, i went into the code and found the behat2 vs Behat2 typo (see patch) which made my original config work.

third I saw the update of the configuration and added the Twig,Behat2 line in behat.yml which also works out:
        emuse\BehatHTMLFormatter\BehatHTMLFormatterExtension:
            name: html
            renderer: Twig,Behat2

now my reports work super!

**Comment by gdobiecki** [comment]
It worked perfectly after adding parameter 'renderer: Twig,Behat2' to behat.yml. Thanks guys!
Closing issue.
