### ISSUE TITLE
A non-numeric value encountered in FeatureContext.php

### ISSUE THREAD

**Issue by fabianderijk** [dutchiexl/BehatHtmlFormatterPlugin#131]
When using this plugin combined with php 8.1 I get the following error message when running my behat tests:

┌─ @BeforeScenario # FeatureContext::prepareTestFolders()
  │
  ╳  Warning: A non-numeric value encountered in /var/www/html/vendor/emuse/behat-html-formatter/features/bootstrap/FeatureContext.php line 77
  │

This is caused by the call to the microtime() function without the float parameter set to true. This should be fixed IMHO.

I will create a PR for this, including the move to Twig 3.

**Comment by fabianderijk** [comment]
I've created PR #132 for this issue

**Comment by PurHur** [comment]
Done.

Branch: 2.0 
Tag: v2.0.0
