### ISSUE TITLE
Fix for depricated file_exists on null in PHP 8 

### ISSUE THREAD

**Issue by danielangelov91** [dutchiexl/BehatHtmlFormatterPlugin#133]
Please replace:
https://github.com/dutchiexl/BehatHtmlFormatterPlugin/blob/ecc2d56d9e9dfd3af4fbf469ed2d0c3499f8d650/src/Classes/Scenario.php#L205
With:
        if (!isset($this->screenshotPath) || !file_exists($this->screenshotPath)) {
            return false;
        }

**Comment by PurHur** [comment]
Done
