### ISSUE TITLE
Twig rendering not working on docker slave with oracleLinuxSlim 8.

### ISSUE THREAD

**Issue by zanderFortinbras** [dutchiexl/BehatHtmlFormatterPlugin#134]
Twig rendering not working on docker slave with oracleLinuxSlim 8 + php 7.4. (index file created but empty. All supporting twig libraries in situ)
Behat2 works but not Twig. The dependencies load correctly and am using the latest version 2.0.0.
What other dependencies are critical to Twig running. 
Zero bytes.

` extensions:
       emuse\BehatHTMLFormatter\BehatHTMLFormatterExtension:
          name: emusehtml
          renderer: Twig,Behat2
          file_name: generated
          print_args: true
          print_outp: true
          loop_break: true`
          
          
![image](https://github.com/dutchiexl/BehatHtmlFormatterPlugin/assets/133135230/031b75b9-4bca-461c-a6cd-25619983e934)

**Comment by zanderFortinbras** [comment]
Any guidance would be very much appreciated.

**Comment by PurHur** [comment]
I never used oracle linux before. I dont know.

This sounds like an issue with the connection to selenium to chrome or something like that. Without knowing your whole setup this is hard to debug.

**Comment by zanderFortinbras** [comment]
Thanks PurHur - 
There is no Selenium involved we are using api / Guzzle

**Comment by zanderFortinbras** [comment]
Finally got to the bottom of this issue it was a memory_limit limitation in php.ini. I set it to -1
