### ISSUE TITLE
Feature request: include echo/print messages in the report

### ISSUE THREAD

**Issue by danyc** [dutchiexl/BehatHtmlFormatterPlugin#15]
Hello,

Cool stuff, but I'm missing a small feature: I have cases when I log some messages to console (using print command) and these messages are not included in the .html report (I can see them in the regular "pretty" report). 

For example, when a step fails, I take a screenshot and log the path and name:

> Screenshot at: D:\blabla\screenshots\2015-05-12_17-36-22_55520fe6d2a17.png

If this line would be included in the html report, maybe I could go further and change it to match a < img > tag which would actually directly display the image in the report. Am I asking too much? :)

I have only one month of experience with Behat, so I'm not capable of extending your code by myself.
If you have other suggestions, please let me know.

Thank you.

**Comment by dutchiexl** [comment]
This would be something I could investigate, but I will need some time.
