### ISSUE TITLE
Update README.md in order to avoid InvalidConfigurationException

### ISSUE THREAD

**Issue by legovaer** [dutchiexl/BehatHtmlFormatterPlugin#16]
I litteraly copied/pasted the settings from the README file. This results in an error;

`[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]
  Unrecognized option "print_table" under "testwork.emusehtml"`

**Comment by lmrafael** [comment]
sorry.
use print_args. I was going to commit a fix with futher changes. But got behind on them. Will fix the READMe tonight (+-8h form now).

sorry again. I know its a critical thing.
