### ISSUE TITLE
Version TAG and License

### ISSUE THREAD

**Issue by erickmoraes** [dutchiexl/BehatHtmlFormatterPlugin#17]
@dutchiexl, you have been doing a great job with the formatter plugin. 
Could you create a version tag - stable -  and define a license for this project?
Thanks! :smile:

**Comment by lmrafael** [comment]
:+1:

**Comment by dutchiexl** [comment]
Will do

On Thursday, May 21, 2015, lmrafael notifications@github.com wrote:

> [image: :+1:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dutchiexl/BehatHtmlFormatterPlugin/issues/17#issuecomment-104344573
> .

## 

Neal Vanmeert

Mobile:+32 (0)496161622
Email: neal@emuse.be
Site: http://www.emuse.be

**Comment by dutchiexl** [comment]
Added a tag, don't know which licence to add, so will add it later (an all free to use and addapt licence offcourse)

**Comment by dutchiexl** [comment]
Added an MIT licence, if anyone disagrees let me know :)

**Comment by erickmoraes** [comment]
Thanks, @dutchiexl!!
