### ISSUE TITLE
Fatal error on Behat2Renderer

### ISSUE THREAD

**Issue by iuriag** [dutchiexl/BehatHtmlFormatterPlugin#20]
The error above occurs because the method call inside a empty function
I using php 5.4
PHP Fatal error:  Can't use method return value in write context in /home/dbseller/.composer/vendor/emuse/behat-html-formatter/src/Renderer/Behat2Renderer.php on line 333

**Comment by dutchiexl** [comment]
can you post your configuration ?

**Comment by dutchiexl** [comment]
Closed because no more reactions

**Comment by Narinder-Chandi** [comment]
We are seeing this same error. Pleae advise as to what further information we can provide to help fix this.
