### ISSUE TITLE
Hello, I have issue with this plugin

### ISSUE THREAD

**Issue by narozhniyy** [dutchiexl/BehatHtmlFormatterPlugin#21]
I add this to my behat.yml :
formatters:
html:
output_path: %paths.base%/
extensions:
emuse\BehatHTMLFormatter\BehatHTMLFormatterExtension:
name: html
renderer: Twig
file_name: Index
print_args: true
print_outp: true
loop_break: true

And behat show error : [Behat\Testwork\Output\Exception\FormatterNotFoundException]

html formatter is not found or has not been properly registered. Registered formatters: junit, progress, pretty.
Can anybody help me?

**Comment by dutchiexl** [comment]
Yes, you should install the plugin. Are you using composer ?

If so, add this to your required section.

`"emuse/behat-html-formatter": "dev-master",`

**Comment by narozhniyy** [comment]
@dutchiexl Of course i did it, "emuse/behat-html-formatter": "dev-master" in my composer.json in require section

**Comment by dutchiexl** [comment]
Can you add the behat.yml file ? so I can test it out.

Your vendor package contains the emuse/behat-html-formatter folder ?

**Comment by narozhniyy** [comment]
Yes folder exist, part of my .yml file:
 default:
  autoload:
      '': %paths.base%/features/bootstrap
  suites:
      default:
        paths:
          - %paths.base%/features
        contexts:
            - PContext:
                  parameters:
                      base_url: 'http://'
                      auth_url: 'http://'
                      wgc_url: 'http://'
            - PFeeds:
                  parameters:
                      base_url: 'http://'
                      auth_url: 'http://'

  formatters:
    html:
      output_path: %paths.base%/
    extensions:
      emuse\BehatHTMLFormatter\BehatHTMLFormatterExtension:
        name: html
        renderer: Twig
        file_name: Index
        print_args: true
        print_outp: true
        loop_break: true

**Comment by dutchiexl** [comment]
your extensions resided under formatters. It should be on the same level as the formatters, not as a child. can you try that ?

**Comment by dutchiexl** [comment]
I guess this solved your problem ? You are welcome! If there is anything else, let me know.

**Comment by narozhniyy** [comment]
@dutchiexl I move extension part out of formatters, now it look like :
  formatters:
    html:
      output_path: %paths.base%/

  extensions:
    Behat\MinkExtension:
      base_url: 'http://'
      goutte: ~
      browser_name: firefox
      selenium2: ~
    emuse\BehatHTMLFormatter\BehatHTMLFormatterExtension:
      name: html
      renderer: Twig
      file_name: Index
      print_args: true
      print_outp: true
      loop_break: true
There is no error, but feature not work, before I add this in config feature work well

**Comment by dutchiexl** [comment]
The formatter does nothing to the feature, it just renders the response of behat. you could run multiple formatters to see the result in the cli:

bin/behat -f pretty -f html

**Comment by narozhniyy** [comment]
bin/behat --tags "@lb-compare" -f pretty -f html --out report.html

[Behat\Testwork\Output\Exception\BadOutputPathException]

Filename expected as output_path parameter, but got /var/www/behat3/behat/report.html.

I set filename as param in -out

**Comment by narozhniyy** [comment]
@dutchiexl it's create a folder in my directory [/report.html/], with assets (twig's css and js), but test doesn't work, do you have any ideas?

**Comment by dutchiexl** [comment]
what do you mean with: test doesn't work ?

**Comment by narozhniyy** [comment]
@dutchiexl   [Behat\Testwork\Output\Exception\BadOutputPathException]  
  Filename expected as `output_path` parameter, but got `/var/www/behat3/behat/report`. 

error, autotest not work

**Comment by dutchiexl** [comment]
No sorry, this does not mean anything to me. Your problem is very vague

**Comment by narozhniyy** [comment]
@dutchiexl  When I add this to my .yml config my test doesn't work :
  formatters:
    html:
      output_path: %paths.base%/

  extensions:
    emuse\BehatHTMLFormatter\BehatHTMLFormatterExtension:
      name: html
      renderer: Twig
      file_name: Index
      print_args: true
      print_outp: true
      loop_break: true
When I remove this from .yml test work.

**Comment by dutchiexl** [comment]
can you remove the trailing slash from the output path,

or maybe add a folde

output_path: %paths.base%/html

**Comment by narozhniyy** [comment]
@dutchiexl  No It's doesn't help me, with html report test not work, without work well, I am sure, issue in .yml config file

**Comment by dutchiexl** [comment]
If you say: test not work, what doesn't work ?
- Nothing happens ?
- It throws an error ? what error ? ......
  If you want me to help, you have to gime me something to work with. "Test not work" is something I can't help you with without giving me all the information .

**Comment by narozhniyy** [comment]
@dutchiexl  sorry but i several times send you errors:

  [Behat\Testwork\Output\Exception\BadOutputPathException]  
  Filename expected as `output_path` parameter, but got `/var/www/behat3/behat/report.html`.  

behat [-s|--suite="..."] [-f|--format="..."] [-o|--out="..."] [--format-settings="..."] [--init] [--lang="..."] [--name="..."] [--tags="..."] [--role="..."] [--story-syntax] [-d|--definitions="..."] [--append-snippets] [--no-snippets] [--strict] [--rerun] [--stop-on-failure] [--dry-run] [paths]

nothing change

**Comment by narozhniyy** [comment]
@dutchiexl I resolved this issue I run test as : 
bin/behat --tags "@lb-compare" -f pretty -f html --out report.html
And have error, now I run test by string : 
bin/behat --tags "@lb-compare" -f pretty -f html
and all work fine thanks)

**Comment by dutchiexl** [comment]
Ok, I was looking into it, but didn't immediately find an answer for you
