### ISSUE TITLE
Add information on installation to README

### ISSUE THREAD

**Issue by legovaer** [dutchiexl/BehatHtmlFormatterPlugin#22]
Now that more and more people are starting to use this extension, it might be useful to add some information on the README file about installing this extension. I know, this seems to be straight forward but I'd expect a lot of issues coming in with questions on how to install this extension!

Another suggestion might be using [Read the docs](http://www.readthedocs.org). But that might be a bit overkill yet.

**Comment by dutchiexl** [comment]
You are absolutely right. I will update the readme and look into the read the docs.

**Comment by dutchiexl** [comment]
Expect this to be done somewhere over the weekend ;)

**Comment by legovaer** [comment]
Also consider adding the extension to [Packagist](https://packagist.org/about) ;)

**Comment by dutchiexl** [comment]
that is allready the case: https://packagist.org/packages/emuse/behat-html-formatter

**Comment by legovaer** [comment]
Sorry, my bad!

**Comment by dutchiexl** [comment]
np!

**Comment by dutchiexl** [comment]
Do you have a good example on an installation (in mind) for another plugin of any kind, which I could use as a base.

If not I will look for one.
