### ISSUE TITLE
Adding the saving of screenshots and HTML dumps

### ISSUE THREAD

**Issue by DaSayan** [dutchiexl/BehatHtmlFormatterPlugin#25]
Hello,

I have a proposition of a new feature to add :
- Generate a screenshot and a dump of the HTML code of the page when a scenario fails, and save them into a directory that will be defined by the user
- Give access from the HTML report to these files with links (Twig, Behat 2)

Also, this generating would be optional and could be deactivated.
It would be also possible, if the user wants it, to generate these files after each steps even if there is no error (to keep a trace of each step of the scenario, could be useful when tests are running with a headless browser like phantomJS)

Do you think adding this feature is a good idea or it is misappropriate regarding the purpose of the plugin ?

I have a little portion of code that actually work with Selenium 2 driver (and so PhantomJS), I think it could be possible to adapt it.

**Comment by dutchiexl** [comment]
I believe this functionality should not be implemented inside this plugin, but rather inside it's own plugin. Then a communication between the plugins should be set up so that you can indeed access the images and html dumps from within the HTML report.

Anyone else has an opinion on this matter? please comment.

**Comment by svemir** [comment]
I agree that it belongs to a separate plugin. We are currently using this one to take screenshots of all steps: https://github.com/alexandresalome/journal-extension

**Comment by DaSayan** [comment]
Ok, I understand.
I will see eventually to develop this feature into a separate plugin, and make it compatible with this plugin to integrate the access from within the HTML report to the files

I think you can close this issue if you want :)
