### ISSUE TITLE
Different filenames for every test 

### ISSUE THREAD

**Issue by rslid** [dutchiexl/BehatHtmlFormatterPlugin#29]
Hi,
The plugin is great and Im using it regularly for generating reports. I have only one question.
Is it possible to avoid the overwriting of the base file ? My goal is to have different html file for every test or at least for every test suite. Can you give me some directions how to approach this ?

Regards

**Comment by dutchiexl** [comment]
simple, remove this line from your config file:

file_name: Index

**Comment by rslid** [comment]
Thanks! It was simple one... The docs had it, sorry for missing it. 

Last question, probably stupid again but ... - is there any way to extract the name of used behat profile and include it in the FileOutputPrinter.php ?

**Comment by dutchiexl** [comment]
Not at the moment, sorry
