### ISSUE TITLE
New template - WP

### ISSUE THREAD

**Issue by fonsecas72** [dutchiexl/BehatHtmlFormatterPlugin#32]
Hi @dutchiexl , would you accept another template?

I have made this one with another extension of mine:
https://rawgit.com/fonsecas72/show/master/index.html
I like your implementation and I'm willing to improve it if you are interested. I would like to add:
- add option to chose a template - this is mandatory;
- background knowledge - It seems that your template replicates the background in each scenario which does not help with visualization. My extension creates a special case for scenarios with background and I can replicate that logic here;
- percentage of passing, failing, skipped, pending for suites and scenarios - It seems that you don't have this logic implemented yet. 

You don't need to commit this new template if don't want to. It is enough to me to have this features implemented.
Perhaps later we can gather our efforts in creating a better template using both templates?

**Comment by dutchiexl** [comment]
Ok, I think the plugin should need a container to register templating engines against.

This means I need to write interfaces so other plugins can hook into this one to add templates.

I am very willing to do this, but I will have to search for time.

**Comment by fonsecas72** [comment]
@dutchiexl can't we just create a config (array) option like "render settings" or something and pass it to the BehatHTMLFormatter and then set it in BaseRenderer for every render engine?

**Comment by fonsecas72** [comment]
btw, I'm willing to do this, I just have to understand what you would accept so my work is not in vain :)

**Comment by dutchiexl** [comment]
Yes I would accept, if the quality is good. Can we sit together somehow to discuss how we would implement?
