### ISSUE TITLE
[question] how do you usually test the templates?

### ISSUE THREAD

**Issue by fonsecas72** [dutchiexl/BehatHtmlFormatterPlugin#35]
Sorry my ignorance.

**Comment by dutchiexl** [comment]
What templates are we talking about ?

**Comment by fonsecas72** [comment]
Any. When you change something how do you know if everything is working?

**Comment by dutchiexl** [comment]
the templates are not tested at the moment.

**Comment by fonsecas72** [comment]
So, just to be clearer, you check if this extension is working by running it against one of your own projects?

**Comment by dutchiexl** [comment]
at the moment, yes

**Comment by fonsecas72** [comment]
ok, ty
