### ISSUE TITLE
Make screenshot on failure

### ISSUE THREAD

**Issue by tikolakin** [dutchiexl/BehatHtmlFormatterPlugin#36]
Hi there
I've noticed that we already have implementation of making screenshot on failure
But it seems not working pretty well or easy
Is it possible to have not only screenshot for each feature but rather each steps that failed?
So, for ex. a feature has a few scenarios some of them are success and some failed and we'd able to view what exactly was on the page when steps couldn't pass.
btw. thanks guys for this very useful feature

**Comment by dutchiexl** [comment]
I would have to look into this

**Comment by fonsecas72** [comment]
Just as a reminder, we should document this (add to the README) when we're ready.

**Comment by jroy-998** [comment]
Hi,

Sorry if this is late, but only just got round to looking at this.

I did the original screenshot changes (admittedly, in a rush). 

I'm looking at making a few improvements, including screenshots at scenario level and not displaying the screenshot link if the file is not present.

@tikolakin would you be able to run a quick test once I've made the changes?

**Comment by jroy-998** [comment]
See https://github.com/dutchiexl/BehatHtmlFormatterPlugin/pull/45

I've changed screenshots to show in the failed step, rather than at feature level.

It requires a slightly different setup, but I've updated this in the README.

If you want to give it a go and let me know your thoughts?
