### ISSUE TITLE
Fatal error on behat launch

### ISSUE THREAD

**Issue by ianmoone** [dutchiexl/BehatHtmlFormatterPlugin#44]
Hi,

I get the following error when I launch my tests suite : 
PHP Fatal error:  Call to undefined method Behat\Gherkin\Node\StepNode::getKeyword()

Don't know what to do ?

Btw, this extension is a great idea

**Comment by dutchiexl** [comment]
It seems like Behat or Gherkin is missing, can you check they are installed ?

**Comment by ianmoone** [comment]
Here is an extract of my composer.json : 
"require": {
        "behat/behat": "~3.0@dev",
        "behat/mink-extension": "2.0._@dev",
        "behat/mink": "_",
        "behat/mink-sahi-driver": "*",
        "symfony/finder": "~2.4",
        "symfony/process": "~2.4"
},

Behat should be installed with this ?

**Comment by dutchiexl** [comment]
can you remove the @dev from the behat ?

Can you check if this file exists:
vendor/behat/gherkin/src/Behat/Gherkin/Node/StepNode.php and getKeyword is a function in it ?

**Comment by ianmoone** [comment]
removed @dev and ran composer update : can't launch my suite anymore (will look into that)
error = `Behat\MinkExtension\Extension` extension file or class could not be located.

The file mentioned exists (after composer update) and getKeyword is a function in it

**Comment by dutchiexl** [comment]
Maybe remove the dev from mink as well ?

**Comment by ianmoone** [comment]
Resolved by updating Behat\MinkExtension/Extension to Behat\MinkExtension in behat.yml

Closing the issue
Thnaks for your help
