### ISSUE TITLE
Add the exception on feature detail view.

### ISSUE THREAD

**Issue by dutchiexl** [dutchiexl/BehatHtmlFormatterPlugin#5]
When opening the detail view of a feature, the failed steps should be able to display the exception in an intuitive way.

The steps allready have the exception in their class when rendered, but are not yet rendered in the HTML.

**Comment by lmrafael** [comment]
Damn, I missed this one. I already addressed this Issue and implemented it on my MR. :)

**Comment by lmrafael** [comment]
@dutchiexl: can it be closed? :)
