### ISSUE TITLE
Add embed screen to report

### ISSUE THREAD

**Issue by narozhniyy** [dutchiexl/BehatHtmlFormatterPlugin#52]
Hi guys, I wanted add screenshot to report and add your code (The facility exists to embed a screenshot into test failures.). And I have some questions to you:
What about takeScreenshot() method? I didn't find this method in your source, if it's should be my method? how I can add already exists screenshot to your Twig report?

**Comment by jroy-998** [comment]
Hi,

What WebDriver are you using? You will need to use your WebDriver's screenshot functionality in order to take a screenshot and name it accordingly.

The takeScreenshot() method is just an example from the WebDriver I use (Facebook WebDriver).
