### ISSUE TITLE
reference on packagist

### ISSUE THREAD

**Issue by gdobiecki** [dutchiexl/BehatHtmlFormatterPlugin#6]
hi,
I hope it's a good place for that, but reference on packagist is not updated. Now it says "reference: c9a0be3" which is more than 30 commits ago. So now to get the latest version I need to write in composer.json "emuse/behat-html-formatter": "dev-master#3e372584755b81bfcd6e0611eb644ccb7cda4efe". Is there a chance to update reference on packagist?
Cheers

**Comment by throup** [comment]
As a temporary solution, try adding this to the end of your `composer.json`:

```
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/dutchiexl/BehatHtmlFormatterPlugin.git"
    }
  ]
```

Composer will then ignore the version lock at packagist and it will grab the latest commit from the master branch.

**Comment by dutchiexl** [comment]
I am very sorry for this. something must have gone wrong when I set up the auto update. I updated everything, the package and the service hook, so everything should be fine now.

Can you confirm so that I can close this ?

**Comment by gdobiecki** [comment]
@dutchiexl yes, it works fine, now. thanks!
