### ISSUE TITLE
Issue with html when both Twig, Behat2 given as renderer

### ISSUE THREAD

**Issue by maheshmanjunath01** [dutchiexl/BehatHtmlFormatterPlugin#67]
Hi,

I had configured the emuse within .yml file as below:
 emuse\BehatHTMLFormatter\BehatHTMLFormatterExtension:
        name: html
        renderer: Twig,Behat2
        print_outp: true
        file_name: index
        print_args: true
        loop_break: true

I used both format because whenever there is a fatal error or something Twig does not give any result. Behat2 gives result till where it was executed

Issue:
When result was generated in html format it had both format within   but when TWIG  results were it did not show any tests.

Can anybody  please let me know how to resolve this?

**Comment by PurHur** [comment]
On execution you can specify the Format via --format html
