### ISSUE TITLE
Report not loading charts

### ISSUE THREAD

**Issue by lmrafael** [dutchiexl/BehatHtmlFormatterPlugin#7]
Hey there, 
the generated report doesn't seems to be rendered with the correct path to the ChartJs (and the style.css as well).

The path where it looks for the js and css is: %path_to_generated_report%/assets/

Is it happening with anyone else or is just me doing something wrong on the configuration?

**Comment by rodrigoaguilera** [comment]
I added the assets folder to the same folder the report.html is going to be

**Comment by lmrafael** [comment]
I ended up doping that as well. Just wondering if there is a smarter way of doing it...

Looking up if there is any way to capture the js, CSS and imagens used in the twig after the render so I can move them.

Thanks by the way

**Comment by dutchiexl** [comment]
Yes, I am still looking for the best way to do this. If anyone has any suggestions, let me know.

**Comment by leevigraham** [comment]
Maybe a post post-install-cmd that copies the assets into a default location?

**Comment by dutchiexl** [comment]
That sounds like a good idea. If no one has a better idea, I will implement this later.

**Comment by dutchiexl** [comment]
I have added some functions in the report wrtie function that check if the assets folder exists in the report destinations folder, and if not, it creates it.

**Comment by dutchiexl** [comment]
Can someone verify if it works(for me it does). So we can close this issue.
