### ISSUE TITLE
Tag new release with latest changes

### ISSUE THREAD

**Issue by dashav** [dutchiexl/BehatHtmlFormatterPlugin#80]
Could you please tag a release with the latest changes? 
The last release was in 2015 and old code is automatically loaded when follow setup instruction. 
Many improvements and bug fixes are in the master branch only now, so you have to load it directly from repo now:

```
  "require-dev": {
    "emuse/behat-html-formatter": "dev-master@dev"
  },
  "repositories": [
    {
        "url": "https://github.com/dutchiexl/BehatHtmlFormatterPlugin.git",
        "type": "git"
    }
  ]
```

**Comment by hason** [comment]
@dashav Why did you close this issue?
