### ISSUE TITLE
Recommendation, question about print last response

### ISSUE THREAD

**Issue by adyballa** [dutchiexl/BehatHtmlFormatterPlugin#9]
Is there a way to print last response. This would be very useful.

**Comment by dutchiexl** [comment]
In what context do you need this, maybe I can do some kind of verbose ?

**Comment by adyballa** [comment]
I recognize this extension, while testing on a debian server. I debugged and couldnt get an output, just with "print last response". Unreadable. As I piped it to an html-file i could see page and the error in the browser.
I've seen that is just an echo. So is there a way to handle stdout? A verbose or debug  would be enough in the sense that it prints stdout and you can do with it what you want.

**Comment by dutchiexl** [comment]
I will look into it as soon as possible

**Comment by dutchiexl** [comment]
I don't really understand what you are trying to achieve. If there are exceptions or errors, they would be rendered in the stdout. If not, the HTML file is created ...

**Comment by adyballa** [comment]
At the end I try to achieve to have a browser-version of "print last response".
What is easy to achieve with a feature.
I think you're right.
