### ISSUE TITLE
Html report has only css and a div, no other content

### ISSUE THREAD

**Issue by sswarupa2017** [dutchiexl/BehatHtmlFormatterPlugin#91]
I have setup behat.yml 

formatters:
    pretty: true
    html:
      #output_path: %paths.base%/build/html/behat   
      output_path: tests/behat/build/html/behat
             
  extensions:
    Behat\MinkExtension:
      javascript_session: selenium2
...

  Behatch\Extension: ~   
    emuse\BehatHTMLFormatter\BehatHTMLFormatterExtension:
      name: html
      renderer: Twig,Behat2
      file_name: Automation
      print_args: true
      print_outp: true
      loop_break: true

I am getting the Filename.html and assets folder at the output_path but not able to see any content other than the css and the content below:
...

                #behat .jq-toggle-opened > h2:after,
                #behat .jq-toggle-opened > h3:after {
                    content:'';
                    font-weight:bold;
                }

                #behat .scenario > ol li,
                #behat .scenario .examples > ol li {
                    border-left:none;
                }
            </style>
        </head>
        <body>
        <div id='behat'>
        <div class="suite">Suite : default</div>

The snippet above is from the end of the file.

Pl. let me know if I am missing anything.

**Comment by PurHur** [comment]
Probably your testrun throwed an exception in the first step of your suite.
