### ISSUE TITLE
screenshot not added on test report

### ISSUE THREAD

**Issue by litodagodog** [dutchiexl/BehatHtmlFormatterPlugin#92]
failed screenshot is/are not added in test report
can you please help me how to add this one?

also i want to take screenshots on all passed test cases

**Comment by donkidd** [comment]
For the Failed steps: I'm assuming that you followed the Setup instructions in the README.md? 
As for the Passed Tests, I would assume that you will need to modify the extension to do that. When would you want to take a screenshot on the passed tests? Would it be some "@afterScenario" kind of thing?

**Comment by PurHur** [comment]
There were huge problems in the pathes. Its fixed now and will be fixed even better in the future with #88
