### ISSUE TITLE
Additional output in reports

### ISSUE THREAD

**Issue by Mpreyzner** [dutchiexl/BehatHtmlFormatterPlugin#93]
Is it possible to add custom output to html? 
I have some additional information echo'ed in after step for failed tests which is super useful for debugging, but it won't show in html output.

**Comment by donkidd** [comment]
Straight out of the repo no, I don't think that is possible, I would think that you would need to fork the project and then probably modify the BehatHTMLFormatter.php so that you can display it how you want, and maybe the renderer so it gets put in the correct spot.
